### ISSUE TITLE
Weird communication flow when trying to send EMPTY ACK

### ISSUE THREAD

**Issue by therealprof** [chrysn/aiocoap#116] opened 2018-07-20 09:02 UTC
As mentioned in #109 I'd like to send an EMPTY ACK as reaction to a POST to send the real answer as a separate message in another CON which is explicitly allowed as per https://tools.ietf.org/html/rfc7252#section-5.2.2 .

However instead of sending an EMPTY ACK straight away I get an immediate EMPTY CON and a short while (presumably the `EMPTY_ACK_DELAY` looking at the wireshark capture) after an EMPTY ACK which does not make a lot of sense.

```
DEBUG:coap-server:Incoming message <aiocoap.Message at 0x101a2c400: Type.CON POST (MID 49857, token 4475) remote <_Connection at 0x101a01400 on transport <_SelectorDatagramTransport fd=8 read=polling write=<idle, bufsize=0>>, active>, 1 option(s)>
DEBUG:coap-server:New unique message received
WARNING:coap-server:Response does not carry response code (<Code 0 "EMPTY">), application probably violates protocol.
DEBUG:coap-server:Sending message <aiocoap.Message at 0x101a2c9b0: Type.CON EMPTY (MID 5675, token 4475) remote <_Connection at 0x101a01400 on transport <_SelectorDatagramTransport fd=8 read=polling write=<idle, bufsize=0>>, active>>
DEBUG:coap-server:Exchange added, message ID: 5675.
DEBUG:coap-server:Sending empty ACK: Response took too long to prepare
DEBUG:coap-server:Sending message <aiocoap.Message at 0x101a2c748: Type.ACK EMPTY (MID 49857, empty token) remote <_Connection at 0x101a01400 on transport <_SelectorDatagramTransport fd=8 read=polling write=<idle, bufsize=0>>, active>>
```

**Comment by chrysn** [comment] 2018-09-24 14:16
aiocoap does not expect the application to do any of the empty ack handling by itself; especially, it expects responses to be returned from it, not empty messages (for NoResponse, see #109, that's solved differently now but is solved).

I can't tell easily from the question what exactly you were attempting, but if you wanted your code to not send any response, please just retry with the new mechanism outlined in 0d09b2e (Note that as long as you use render_\* methods and your client sends a No-Response option, things work automagically and you can just return the response you'd give normally). If you just wanted to send an empty ack and later reply, you can let the library handle the empty ack and "block" the response handler until you have a definite response.

If either of that solves your issue, please close this item; otherwise let me know how it fails know, and what exactly your handler is trying to do.

**Comment by therealprof** [comment] 2018-09-24 14:18
Thanks, I'm trying right at this moment.

**Comment by chrysn** [comment] 2018-09-24 14:28
> Hm, weird... need to debug some more, I'm just getting: `OSError: [Errno 65] No route to host`

You may want to check which IP versions are involved; aiocoap does *not*
handle situations where it receives a AAAA (IPv6) record from DNS but
ony has IPv4 routes available gracefully.

**Comment by therealprof** [comment] 2018-09-24 14:36
Right, using the IPv4 address works.

**Comment by therealprof** [comment] 2018-09-25 09:02
So I tried this but it did not quite work. Let me give a little bit of background: I'm trying to write a LwM2M client which simulates the BOOTSTRAP behaviour of mbedOS.

The basic workflow is this:
* Client sends a CON POST to /bs?ep=endpoint
* Server sends ACK 2.04 Changed
* Server sends various CON PUT/DELETE, all properly ACKed by Client
* Server sends  a CON POST to /bs (to indicate a BOOSTRAP finish)
* Most clients would send a ACK 2.04 Changed but mbedOS sends an empty ACK and tries to send a CON with 2.04 Changed in a later message

So the last step is where my problems are. 

When I do 
```
response = Message(code=EMPTY, no_response=True)
```
I (still) will get a warning
```
WARNING:coap-server:Response does not carry response code (<Code 0 "EMPTY">), application probably violates protocol.
```
and it will send a CON, instead of the ACK.

If instead I do
```
response = Message(code=CONTENT, no_response=True)
```
it will send an ACK with code 2.05 Content (but no payload) to Uri-Path /bs

I played around with the latest change and this line looks fishy to me:
```
            no_response = (message.opt.no_response or 0) & (1 << (message.code >> 5) - 1) != 0
```

Did you mean to use a logical *and* instead
```
            no_response = (message.opt.no_response or 0) and (1 << (message.code >> 5) - 1) != 0
``` 
?

At least this will happily turn a response into an empty ACK, i.e. work as intended.

**Comment by chrysn** [comment] 2018-09-25 10:07
> ```
>             no_response = (message.opt.no_response or 0) & (1 << (message.code >> 5) - 1) != 0
>             no_response = (message.opt.no_response or 0) and (1 << (message.code >> 5) - 1) != 0
> ```

No, the '&' is fine here, it's bit-wise arithmetic that checks whether
the code's bit it set in the no_response option. The response will only
be suppressed if the code is one of the classes indicated in the
no_response option.


> * Most clients would send a ACK 2.04 Changed but mbedOS sends an empty
> ACK and tries to send a CON with 2.04 Changed in a later message

If this behavior is what you're trying to emulate, you're in very deep
details of CoAP that must not, per the specification, matter to the
outcome -- and are therefore not configurable in aiocoap.

It's understandable that mbed does it that way because it's easier, and
it's not wrong, but any system it interacts with to which that makes a
difference, that system is broken.

> ```
> return Message(code=EMPTY, no_response=True)
> ```

Now you can't reproduce this *directly* in aiocoap -- the response
returned from the handler must always be the final response, not any
intermediate response that may or may not be appropriate (and is thus
complained about as protocol violation -- not because it's wrong to be
sent, but it's wrong to be sent as a final response).

What you *can* do, provided you don't want to emulate the timing to the
sub-second precision, is to add an

```
await asyncio.sleep(0.2)
```

in your handler. That delays the final response, and in the mean time,
the 100ms hold-off that asyncio internally has (the EMPTY_ACK_DELAY)
passes, and aiocoap will *on its own* send an empty ack to prevent
retransmissions on the server's side.


> So I tried this but it did not quite work. Let me give a little bit of
> background: I'm trying to write a LwM2M client which simulates the
> BOOTSTRAP behaviour of mbedOS.

That being said, what LWM2M specifies as "bootstrap" (the process you
described below) is a subset of the Resource Directory functionality
specified (work in progress) at [1].

So unless you're aiming for a package-by-package emulation, you might be
able to use components built into aiocoap as well: aiocoap-rd can
provide the part that serves /bs, and aiocoap.resourcedirectory.client
contains a component that you can add into a device application to
register there.

Now your application might have particular expectations towards where
the directory is located (eg. a hardcoded "/bs" somewhere), but that can
be changed on the server side in code (currently it's not paramized and
aiocoap calls it /resourcedirectory, but if there's need for it...).

So this is not part of the issue here at hand, but I'd invite you to
play around with the shipped resource directory, and happily help out to
make it work with the lwm2m mbed implementation.

[1]: https://tools.ietf.org/html/draft-ietf-core-resource-directory-14

**Comment by therealprof** [comment] 2018-09-25 12:48
> No, the '&' is fine here, it's bit-wise arithmetic that checks whether
the code's bit it set in the no_response option. The response will only
be suppressed if the code is one of the classes indicated in the
no_response option.

? I don't understand. Which classes would that be?

> It's understandable that mbed does it that way because it's easier, and
it's not wrong, but any system it interacts with to which that makes a
difference, that system is broken.

Huh? No, actually it's harder than to piggyback the response.

But you're right, my system is broken which is the reason why I want to replicate the problematic behaviour with aiocoap.

> in your handler. That delays the final response, and in the mean time,
the 100ms hold-off that asyncio internally has (the EMPTY_ACK_DELAY)
passes, and aiocoap will *on its own* send an empty ack to prevent
retransmissions on the server's side.

That seems to work much better. Thanks. Will check whether this solves my problems.

May I suggest to introduce a slightly more elegant way of achieving the the same without having to rely on implementation specifics?

> So this is not part of the issue here at hand, but I'd invite you to
play around with the shipped resource directory, and happily help out to
make it work with the lwm2m mbed implementation.

I'm not trying to make mbedOS work, merely trying to make our server compatible with mbedOS by emulating the behaviour and eventually setting up an automated test suite. `aiocoap` seems to be much more suitable for than than e.g. `CoAPthon`...

> So this is not part of the issue here at hand, but I'd invite you to
play around with the shipped resource directory, and happily help out to
make it work with the lwm2m mbed implementation.

I will check it out, thanks.

**Comment by therealprof** [comment] 2018-09-25 13:38
> If the EMPTY_ACK_TIMEOUT were configurable (so you could set it to 0),
would you consider that an elegant solution?

That would be great. I can imagine people might also like to adjust that to a higher value. An automatism like that can be very elegant if it is nicely documented. ;)

**Comment by chrysn** [comment] 2018-09-25 14:45
Tracking configurable EMPTY_ACK_TIMEOUT in #75, closing this. Thanks for your input!

**Closed by chrysn** 2018-09-25 14:45 UTC
