### ISSUE TITLE
Support for asynchronous calls?

### ISSUE THREAD

**Issue by Hedda** [chrysn/aiocoap#78] opened 2017-06-14 09:04 UTC
Is it possible to support async calls? See dicussion: https://www.domoticz.com/forum/viewtopic.php?f=65&t=17312

**Comment by chrysn** [comment] 2017-06-14 09:23
I don't quite understand -- aiocoap *always* does asynchronous calls.

If you want to get callbacks (eg. because aiocoap is running in its own thread in a program that doesn't use asyncio), it should be possible to do something like

```
def called_from_main_program_as_a_new_thread(..., callback_to_main_thread):
    _await = asyncio.get_event_loop().run_until_complete
    ctx = _await(Context.create_client_context())
    response = _await(ctx.request(...).response)
    callback_to_main_thread(response.payload)
```

but I'd rather understand what you actually need in domoticz. What is the plugin architecture, does each plugin get its own process, or are they supposed to work?

**Comment by chrysn** [comment] 2017-06-14 09:47
Looking throuhg <https://www.domoticz.com/wiki/Developing_a_Python_plugin>, it seems that all communication of Python plugins must be routed through Domoticz; is that what you are trying to do?

If so, that *could* be done by adding another transport ("DomoticzUDP"), and possibly some adaption so that Domoticz' calls behave like async IO. One function of asyncio is that any blocking calls are avoided, and instead, the operating system is instructed to tell the process when any of the pending operations are done. Domoticz would take the role of the operating system here.

However, I'd recommend against this approach, as not only is it a difficult and long task, but also does Domoticz make an insufficient operating system, in that it (as it seems from the documentation) only allows the program to run when a UDP package on the single established and connected socket comes along, but not again after a given time (CoAP has retransmissions that need to be taken care of), or when an ICMP error message comes along (lack of which creates very bad user experience where connections don't fail but just time out), and doesn't let the plugin create a server.

Short of Domoticz enhancing their plugin adaptor that allows plugins to just use the existing Python infrastructure (I'just seen you already created #1620), my best short-term bet would be to have the plugin fork its own process where it can run full asyncio and do some sort of RPC (probably over TCP as there's no unix socket support) with a shim plugin.

**Comment by ABotelho23** [comment] 2018-03-03 00:46
I'm having similar issues, and found this GitHub issue. Hopefully this is appropriate.

I have a python program that needs to accept and send CoAP requests simultaneously (it's both a client and server) and perform tasks based on received and sent requests in a parallel fashion. From what I've been able to find, asyncio by itself wouldn't work all that well.

Right now, we have our primary python program and one of its threads (let's called it Thread #1). Thread #1 calls the main function of a secondary program which performs a CoAP GET request (via aiocoap). The secondary program returns the payload of the CoAP request back to Thread#1 in the primary program. Thread #1 runs indefinitely. We've done this to try and make our project modular and keep the main program as small as possible. What would be the best approach for this?

**Comment by chrysn** [comment] 2018-03-03 09:28
On Sat, Mar 03, 2018 at 12:47:00AM +0000, Alex Botelho wrote:
> I have a python program that needs to accept and send CoAP requests
> simultaneously (it's both a client and server) and perform tasks based
> on received and sent requests in a parallel fashion. From what I've
> been able to find, asyncio by itself wouldn't work all that well.

This works very well with asyncio, let's try to figure this out.

> Right now, we have our primary python program and one of its threads
> (let's called it Thread #1). Thread #1 calls the main function of a
> secondary program which performs a CoAP GET request (via aiocoap). The
> secondary program returns the payload of the CoAP request back to
> Thread#1 in the primary program. Thread #1 runs indefinitely. We've
> done this to try and make our project modular and keep the main
> program as small as possible. What would be the best approach for
> this? 

I have practically no experience with threading in Python, so take what
I'm proposing with a grain of salt and consider reading up on asyncio in
general at [1], because it might easily be that I'm overly defensive
here, assuming nothing asyncio is threadsafe.

As you use threads, you'll need one that runs the asyncio main loop in
one thread; that thread will not only do all the aiocoap networking but
can also run other libraries' asyncio tasks.

The only thing that this task needs to do by itself is
asyncio.get_event_loop(), pass that loop out of your thread and
loop.run_forever(). Then, whenever you'd use `await x`, you can write
`asyncio.run_coroutine_threadsafe(x, loop)` to get a concurrent
(threading) Future instead of an asyncio Future.

You can have a single context both for server and client operations, so
whatever kicks off aiocoap initially might look like:

    the_asyncio_loop = Future()
    def the_asyncio_thread():
        loop = asyncio.get_event_loop()
        the_asyncio_loop.set_result(loop)
        loop.run_forever()
    thread.start_new_thread(the_asyncio_thread)

    loop = the_asyncio_loop.result()

    protocol = asyncio.run_coroutine_threadsafe(
        asyncio.Context.create_server_context(...),
        loop).result()

    request = aiocoap.Message(uri='coap://localhost/time')
    response = asyncio.run_coroutine_threadsafe(
        protocol.request(request).response,
        loop).result()

(As said, don't trust this; I haven't tried it).

I'd suggest, though, that you move some of the code around request and
response processing into asyncio too, so you have a slimmer interface
than the full aiocoap API that needs to cross the border between thread
and async land.

Please let me know if you run into further trouble or whether this
approach actually works for you!

[1]: https://docs.python.org/3/library/asyncio-dev.html#asyncio-multithreading

**Comment by ABotelho23** [comment] 2018-03-03 23:47
Phenomenal, this was even more then I expected. I'll take a whack at it in the next few days, and I'll let you know!

**Comment by chrysn** [comment] 2018-03-06 17:24
Note to self: it might be handy to have some documentation on how to run aiocoap when you're not subscribed to asynchronous operation, and how to integrate into threading programs.

**Comment by ABotelho23** [comment] 2018-03-09 23:47
Alright we gave things a try again on Wednesday and today, and shuffled around a lot of code. Mostly the idea is we plan on having a GUI front-end running in a thread that can trigger GET and PUT requests, as well as receive requests from other CoAP devices.

All of the code I'm making reference to here is in https://github.com/ABotelho23/aacdnProject/blob/hubCode-flask-testcoroutines/hubAsync.py

We're currently calling sendGet which is a coroutine that puts together a GET request to one of our node devices. sendGet is being called from our instance of testThread (which would be our GUI thread in the final code) to which we passed the loop created in our main thread as well as the client context we created in our main.

`def testThread(loop,protocol):
    print("TEST: In thread",threading.current_thread())
    asyncio.set_event_loop(loop)

    packet = loop.run_until_complete(sendGet(protocol))

    print("TEST: In thread",threading.current_thread())

    print("\n\n!==========REPONSE FROM NODE: ",packet,"==========!\n\n")

    print("TEST: In thread",threading.current_thread())

async def sendGet(context):
  print("ASYNC1: In thread",threading.current_thread())
  targetURI = 'coap://10.0.0.104/blinds/move'

  request = Message(code=GET, uri=targetURI)

  try:
      response = await context.request(request).response
      print("ASYNC2: In thread",threading.current_thread())

  except Exception as e:
      return e
  else:
      return response.payload

def main():

  loop = asyncio.new_event_loop()
  asyncio.set_event_loop(loop)

  root = resource.Site()
  root.add_resource(('.well-known', 'core'),
          resource.WKCResource(root.get_resources_as_linkheader))
  root.add_resource(('test',), TestResource())

  protocol = loop.run_until_complete(aiocoap.Context.create_client_context())

  print('DEBUG: STARTING TEST THREAD...')
  test1 = threading.Thread(target=testThread,args=(loop,protocol,))
  test1.start()
  print('DEBUG: FINISHED STARTING TEST THREAD...\n')

  print('DEBUG: PRINTING FROM MAIN\n')

  #loop.run_forevever()

if __name__ == "__main__":
    main()`

The problem that we've running into is that if we replace "protocol = loop.run_until_complete(aiocoap.Context.create_client_context())" with "protocol = loop.run_forever(aiocoap.Context.create_server_context(root))" to enable server functionality, our GET request is still sent out to our node, but the server functionality in this causes whatever client trying to access the /test resource to re-transmit endlessly. Is that not the proper syntax?

A lot of this stems from us trying to wrap our head around how asynchronous programming works.

**Comment by chrysn** [comment] 2018-03-10 08:06
Hello Alex,

On Fri, Mar 09, 2018 at 03:47:47PM -0800, Alex Botelho wrote:
> The problem that we've running into is that if we replace "protocol =
> loop.run_until_complete(aiocoap.Context.create_client_context())" with
> "protocol =
> loop.run_forever(aiocoap.Context.create_server_context(root))" to
> enable server functionality, our GET request is still sent out to our
> node, but the server functionality in this causes whatever client
> trying to access the /test resource to re-transmit endlessly. Is that
> not the proper syntax?

Well first of all, run_forever takes no arguments -- it'd just run the
loop and whatever tasks are active in it. Also, a server context can
also serve client requests; you only need one. 


One thing that's definitely wrong here is that you set your loop both as
the main thread's and the testThread's main loop -- that's bound to
cause trouble.

Drop main's set_event_loop line, and move the creation of the protocol
into testThread (which now takes one argument less) -- that should do
away with your immediate worries.

Then, I strongly recommend you don't loop.run_until_complete anywhere
where it doesn't need to be; for example, you can replace testThread
with

`
def testThreadWrapper(loop):
    asyncio.set_event_loop(loop)
    loop.run_until_complete(testThread())

async def testThread():
    print("TEST: In thread",threading.current_thread())

    protocol = await aiocoap.Context.create_client_context()

    packet = await sendGet(protocol)

    print("got packet", packet)
`

or something that like so that whereever you use asynchronous code, you
do it from async functions rather than awkwardly blocking around every
second line.

(Nits: for the love of whichever deity you worship, use consistent
indentation!)

This still won't teach you getting data back and forth between threading
and the sync world, but it'll help with your immediate problems.

> A lot of this stems from us trying to wrap our head around how
> asynchronous programming works.

Trust me, if you're used to writing single-threaded applications with
select-based main loops, it's the other way round ;-)

More seriously, though: please consider taking this issue to your
curriculum managers. I've had a glance at the Network Technology
bacheler programme, and as it has a chapter on web programming that
leaves you familiar with threading but unfamiliar with asynchronous
styles, the least they can do is to set up a tutorial group on the
topic.

Best regards
chrysn

**Comment by ABotelho23** [comment] 2018-03-13 00:41
This was extremely helpful for our understanding!

> Well first of all, run_forever takes no arguments -- it'd just run the
> loop and whatever tasks are active in it. Also, a server context can
> also serve client requests; you only need one.
This is what I had read in your docs, but wasn't sure how to actually do it. After more reading of your docs and some reading up on asyncio, I think I have it down now.

I definitely understand much more what you were trying to do in your original reply, and I think I'll follow your initial recommendation of putting all the aiocoap stuff into its own thread. I'll then try a bit of the _threadsafe stuff. Ideally I'd simply want the GUI/test thread being able to have the aiocoap start work in its own event loop in its own thread. Mostly because there will be multiple different places where the aiocoap may receive triggers to process requests from different threads.

We've mostly fixed the indentation. That comes from moving from editing directly on GitHub to starting to code in Atom, which defaults tabs as two spaces!

> Trust me, if you're used to writing single-threaded applications with
> select-based main loops, it's the other way round ;-)
> 
> More seriously, though: please consider taking this issue to your
> curriculum managers. I've had a glance at the Network Technology
> bacheler programme, and as it has a chapter on web programming that
> leaves you familiar with threading but unfamiliar with asynchronous
> styles, the least they can do is to set up a tutorial group on the
> topic.

We're mostly on our own with this. The Web Programming course was more or less complete hand-holding to allow us to "see" how web programming is. The degree mostly focuses on the administration, design and deployment of networks, and not so much the programming of them. Our core courses had us configure devices, not program code for them.

This is also our first go at Python!

We genuinely appreciate the assistance with this. I honestly didn't expect to see such a meaningful response, and I'm thankful you've taken the time to reply at all!

**Comment by ABotelho23** [comment] 2018-03-13 20:56
So we have an implementation that works as intended and gets us the behaviour we are expecting.

This code is pulled from https://github.com/ABotelho23/aacdnProject/blob/hubCode-flask/hubAiocoap.py

It works by passing the event loop to an aiocoap "worker" thread. Sets the event loop to run forever. Then I call protocol = asyncio.run_coroutine_threadsafe(aiocoap.Context.create_server_context(root),coap_loop).result() to create the server context (which as you have shown works for both server and client requests) in the event loop that's in the aiocoap worker thread. From there I take the created context called protocol and I pass it to another thread I create (which could be any thread, really). From that test Thread can call the createRequest coroutine using _threadsafe as an interface to be able to send requests in the aiocoap thread. I've tested it, and currently the test thread sends a request every second with an infinite loop (with an appropriate reply from our node), and it can also receive requests (and appropriately reply to them).

```
async def createRequest(request_type, node_address, node_resource,protocol):
    print("COAP THREAD DEBUG, SENDING REQUEST START: ",threading.current_thread())
    targetURI = 'coap://' + node_address + node_resource

    request = Message(code=GET, uri=targetURI)

    """We don't technically care if the GUI thread blocks, only that the coap thread does"""
    try:
        response = await protocol.request(request).response
    except Exception as e:
        return e
    else:
        return response.payload

def aiocoapThread(loop):

    print("COAP THREAD DEBUG #1, setting event loop: ",threading.current_thread())
    asyncio.set_event_loop(loop)

    print("COAP THREAD DEBUG #3, making loop run forever: ",threading.current_thread())
    loop.run_forever()

    print("COAP THREAD DEBUG #4, should this be seen?: ",threading.current_thread())

def testThread(loop,protocol):
    """This thread emulates what would be the GUI in the final product"""
    print("TEST THREAD DEBUG #1: ",threading.current_thread())

    counter = 0
    while True:
        counter += 1
        time.sleep(1)
        packet = asyncio.run_coroutine_threadsafe(createRequest('GET', '10.0.0.101', '/bulb/colours',protocol), loop).result()

        print("\n\n!==========REPONSE #",counter," FROM NODE: ",packet,"==========!\n\n")

        print("COAP THREAD DEBUG #3: ",threading.current_thread())

def main():

    print('DEBUG: STARTING FLASK THREAD...')
    flaskServer = FlaskThread()
    flaskServer.start()
    print('DEBUG: FINISHED STARTING FLASK THREAD...')

    coap_loop = asyncio.get_event_loop()

    root = resource.Site()
    root.add_resource(('.well-known', 'core'),
        resource.WKCResource(root.get_resources_as_linkheader))
    root.add_resource(('test',), TestResource())

    print('DEBUG: STARTING AIOCOAP THREAD...')
    aiocoapWorker = threading.Thread(target=aiocoapThread, args=(coap_loop,))
    aiocoapWorker.start()
    print('DEBUG: FINISHED STARTING AIOCOAP THREAD...\n')

    protocol = asyncio.run_coroutine_threadsafe(aiocoap.Context.create_server_context(root),coap_loop).result()

    print('DEBUG: STARTING TEST THREAD...')
    testInstance = threading.Thread(target=testThread, args=(coap_loop,protocol,))
    testInstance.start()
    print('DEBUG: FINISHED STARTING TEST THREAD...')

    print('ALL THREADS STARTED!\n')

    counter = 0
    while True:
        counter += 1
        time.sleep(3)
        print('MAIN THREAD DEBUG #:',counter, ', PRINTING FROM END OF MAIN\n')

if __name__ == "__main__":
    main()
```

Does this approach seem optimal to you? It most closely resembles your original reply, and also allows us the behaviour we were looking for (all requests/networking in its own thread). I imagine this way we could spin up any number of threads that could ask the aiocoap thread to perform requests on behalf of it.

**Comment by chrysn** [comment] 2018-03-14 07:11
Looks good to me, as far as I can judge; that it works is also a good indicator ;-)

I'll try to keep aiocoap usable for such cases by avoiding to guess the loop.

(Closing issue as I think the thread provides good material for the original question; feel free to keep posting notes or re-open if something related resurfaces.)

**Closed by chrysn** 2018-03-14 07:11 UTC
Labels: documentation, needs info, question
