### ISSUE TITLE
NO module name IN

### ISSUE THREAD

**Issue by itsweet** [chrysn/aiocoap#37] opened 2016-06-06 02:19 UTC
File "C:\Users\Administrator\Documents\python\aiocoap-master\aiocoap\transports\udp6.py", line 20, in <module>
    import IN
ImportError: No module named 'IN'

**Comment by chrysn** [comment] 2016-06-07 13:45
This is a duplicate of https://github.com/chrysn/aiocoap/issues/27, closing it; please subscribe and/or contribute to that bug.

**Closed by chrysn** 2016-06-07 13:45 UTC
