### ISSUE TITLE
OSError: [WinError 10022] An invalid argument was supplied

### ISSUE THREAD

**Issue by 2trc** [chrysn/aiocoap#52] opened 2016-12-07 10:14 UTC
Hi,  
On windows I get this error while running the example fileserver.py or any other examples on http://aiocoap.readthedocs.io/en/latest/examples.html

```
Traceback (most recent call last):
  File "fileserver.py", line 173, in <module>
    loop.run_until_complete(main(**vars(p.parse_args())))
  File "c:\program files (x86)\python35-32\Lib\asyncio\base_events.py", line 387, in run_until_complete
    return future.result()
  File "c:\program files (x86)\python35-32\Lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "c:\program files (x86)\python35-32\Lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "fileserver.py", line 161, in main
    context = await aiocoap.Context.create_server_context(server)
  File "C:\Users\eremtas\Documents\Projects\AppIoT\aiocoap-101\venv\lib\site-packages\aiocoap\protocol.py", line 535, in create_server_context
    transport, protocol = yield from loop.create_datagram_endpoint(protofact, family=socket.AF_INET6)
  File "c:\program files (x86)\python35-32\Lib\asyncio\base_events.py", line 848, in create_datagram_endpoint
    sock, protocol, r_addr, waiter)
  File "c:\program files (x86)\python35-32\Lib\asyncio\selector_events.py", line 90, in _make_datagram_transport
    address, waiter, extra)
  File "c:\program files (x86)\python35-32\Lib\asyncio\selector_events.py", line 997, in __init__
    super().__init__(loop, sock, protocol, extra)
  File "c:\program files (x86)\python35-32\Lib\asyncio\selector_events.py", line 514, in __init__
    self._extra['sockname'] = sock.getsockname()
OSError: [WinError 10022] An invalid argument was supplied
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<FileServer.check_files_for_refreshes() running at fileserver.py:49> wait_for=<Future pending cb=[Task._wakeup()]>>
```

I don't get this error on Ubuntu. it could be something to do with asyncio

Remi

**Comment by chrysn** [comment] 2016-12-07 11:44
@2trc, this looks largely like a duplicate of #27, but I'll leave it open because we might be able to work something out here – this is all a bit tricky for me to debug since I don't have any current Windows machines.

In https://github.com/chrysn/aiocoap/issues/27#issuecomment-134157863, ksrm has suggested dropping the IPv6-related options and placing IPv4 addresses everywhere instead of v6 ones (not the way to go on the long run, but it might get us a working baseline). Could you try and see whether that makes things work on your box?

**Closed** 2016-12-12 20:54 UTC
Labels: help wanted, platform support

**Comment by 2trc** [comment] 2016-12-12 20:55
@chrysn thanks and let's follow one track
